import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

const root = resolve(import.meta.dirname, '../..')
const workflow = name => readFileSync(resolve(root, '.github/workflows', name), 'utf8')

describe('registry protected workflows', () => {
  it('accepts only a release intent id and stops after opening a generated-only PR', () => {
    const source = workflow('registry-release.yml')
    const mainGuard = source.slice(
      source.indexOf('- name: Confirm protected main has not moved'),
      source.indexOf('- name: Verify generated-only diff'),
    )

    expect(source).toContain('workflow_dispatch:')
    expect(source).toContain('releaseIntentId:')
    expect(source).toContain('startsWith(inputs.releaseIntentId, \'release:production:\')')
    expect(source).toContain('\'registry-release-production\' || \'registry-release\'')
    expect(source).toContain('actions/create-github-app-token@v3')
    expect(source).toMatch(/^ {2}pull-requests: read$/m)
    expect(source).toMatch(/CLOUDBASE_API_KEY: \$\{\{ secrets\.CLOUDBASE_API_KEY \}\}/)
    expect(source).toMatch(/CLOUDBASE_ENV_ID: \$\{\{ vars\.CLOUDBASE_ENV_ID \}\}/)
    expect(source).toContain('node scripts/authenticate-cloudbase-ci.mjs')
    expect(source.indexOf('node scripts/authenticate-cloudbase-ci.mjs')).toBeLessThan(source.indexOf('record-ci'))
    expect(source).toContain('release-export')
    expect(source).toContain('git diff --name-only HEAD')
    expect(source).toContain('git ls-files --others --exclude-standard')
    expect(source).toContain('chore(sso-registry): publish')
    expect(source).toContain('--status pr_open')
    expect(source).not.toContain('statusCheckRollup')
    expect(source).not.toContain('gh pr checks')
    expect(source).not.toContain('gh pr merge')
    expect(source).not.toContain('sleep 5')
    expect(source).toContain('vars.SSO_REGISTRY_PRODUCTION_DEPLOY_ENABLED')
    expect(source).toContain('test "$PRODUCTION_DEPLOY_ENABLED" = true')
    expect(mainGuard).toContain('GH_TOKEN: $' + '{{ github.token }}')
    expect(mainGuard).toContain('gh api "repos/$' + '{GITHUB_REPOSITORY}/git/ref/heads/main" --jq .object.sha')
    expect(mainGuard).not.toContain('git fetch origin main')
    expect(source).not.toMatch(/^\s{6}(environment|snapshotId|baseCommitSha):/m)
  })

  it('finalizes a successful CI run from trusted main without executing pull request code', () => {
    const source = workflow('registry-release-finalize.yml')
    const appTokenIndex = source.indexOf('actions/create-github-app-token@v3')
    const verifyIndex = source.indexOf('pnpm sso:registry verify-release')

    expect(source).toContain('workflow_run:')
    expect(source).toContain('workflows: [CI]')
    expect(source).toContain('types: [completed]')
    expect(source).toContain('registry/release-development-*')
    expect(source).toContain('registry/release-production-*')
    expect(source).toContain('startsWith(github.event.workflow_run.head_branch, \'registry/release-production-\')')
    expect(source).toContain('\'registry-release-production\' || \'registry-release\'')
    expect(source).toContain('github.event.workflow_run.event == \'pull_request\'')
    expect(source).toContain('github.event.workflow_run.conclusion == \'success\'')
    expect(source).toMatch(/^ {2}contents: read$/m)
    expect(source).toMatch(/^ {2}pull-requests: read$/m)
    expect(source).toContain('ref: main')
    expect(source).toContain('persist-credentials: false')
    expect(source).not.toContain('ref: $' + '{{ github.event.workflow_run.head_sha }}')
    expect(source).not.toContain('cache: pnpm')
    expect(source).toContain('pulls?state=open&base=main&head=')
    expect(source).toContain('git/ref/heads/main')
    expect(source).toContain('pulls/$PR_NUMBER/files?per_page=100')
    expect(source).toContain('test "$' + '{#changed[@]}" -eq 2')
    expect(source).toContain('contents/$registry_file?ref=$EXPECTED_HEAD_SHA')
    expect(source).toContain('contents/$release_file?ref=$EXPECTED_HEAD_SHA')
    expect(source).toContain('pnpm sso:registry verify-release')
    expect(source).toContain('jq -r \'.intent.baseCommitSha\'')
    expect(source).toContain('jq -r \'.intent.generation\'')
    expect(source).toContain('jq -r \'.releaseIntentId\'')
    expect(source).toContain('actions/create-github-app-token@v3')
    expect(source).toContain('node scripts/authenticate-cloudbase-ci.mjs')
    expect(appTokenIndex).toBeGreaterThan(verifyIndex)
    expect(source).toContain('gh pr merge "$PR_NUMBER" --squash --match-head-commit "$EXPECTED_HEAD_SHA" --delete-branch')
    expect(source).not.toContain('gh pr checks')
    expect(source).not.toContain('statusCheckRollup')
  })

  it('verifies release files before entering environment-scoped deployment jobs', () => {
    const source = workflow('registry-deploy.yml')

    expect(source).toContain('verify-release')
    expect(source).toContain('environment: registry-release')
    expect(source).toContain('environment: production')
    expect(source).toMatch(/CLOUDBASE_API_KEY: \$\{\{ secrets\.CLOUDBASE_API_KEY \}\}/)
    expect(source).toMatch(/CLOUDBASE_ENV_ID: \$\{\{ vars\.CLOUDBASE_ENV_ID \}\}/)
    expect(source.match(/node scripts\/authenticate-cloudbase-ci\.mjs/g)).toHaveLength(2)
    expect(source).toContain('group: sso-registry-production')
    expect(source).toContain('record-deployment')
    expect(source).toContain('"sso-registry-admin":"$' + '{{ github.sha }}"')
    expect(source).not.toContain('SSO_IDENTITY_SIGNING_KEY: $' + '{{ secrets.SSO_IDENTITY_SIGNING_KEY }}')
    expect(source).not.toContain('SSO_TICKET_PRIVATE_KEY: $' + '{{ secrets.SSO_TICKET_PRIVATE_KEY }}')
    expect(source).toContain('vars.SSO_REGISTRY_PRODUCTION_DEPLOY_ENABLED == \'true\'')
    expect(source.indexOf('verify-release')).toBeLessThan(source.indexOf('environment: production'))
  })
})
